//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetalImpactApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetalImpactApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous annulez toutes les modifications effectuées sur ce texte et recommencer?.
        /// </summary>
        internal static string CancelAllModificationsAndRestart {
            get {
                return ResourceManager.GetString("CancelAllModificationsAndRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous annulez toutes les modifications effectuées sur ce texte et fermer la fenêtre? Cette review ne sera pas modifiée..
        /// </summary>
        internal static string CancelAllOperationsAndQuit {
            get {
                return ResourceManager.GetString("CancelAllOperationsAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulation.
        /// </summary>
        internal static string CancellationLabel {
            get {
                return ResourceManager.GetString("CancellationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer?.
        /// </summary>
        internal static string CloseQuestion {
            get {
                return ResourceManager.GetString("CloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuer.
        /// </summary>
        internal static string ContinueLabel {
            get {
                return ResourceManager.GetString("ContinueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes vous sûr de vouloir quitter le programme?.
        /// </summary>
        internal static string DoYouWantToQuitProgram {
            get {
                return ResourceManager.GetString("DoYouWantToQuitProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        internal static string ErrorLabel {
            get {
                return ResourceManager.GetString("ErrorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue ! Détail : .
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer.
        /// </summary>
        internal static string GenerateLabel {
            get {
                return ResourceManager.GetString("GenerateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La date de dernière génération des Xmls doit être inférieure à la date d&apos;aujourd&apos;hui.
        /// </summary>
        internal static string GenerationDateMustBeBeforeToday {
            get {
                return ResourceManager.GetString("GenerationDateMustBeBeforeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opération stoppée !.
        /// </summary>
        internal static string OperationStopped {
            get {
                return ResourceManager.GetString("OperationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez sélectionner un type de destination.
        /// </summary>
        internal static string SelectADestinationType {
            get {
                return ResourceManager.GetString("SelectADestinationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez obligatoirement selectionner une action à faire pour ce changement..
        /// </summary>
        internal static string SelectAnActionToPerform {
            get {
                return ResourceManager.GetString("SelectAnActionToPerform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez selectionner au moins une opération à effectuer.
        /// </summary>
        internal static string SelectAtLeastOneOperation {
            get {
                return ResourceManager.GetString("SelectAtLeastOneOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêt en cours....
        /// </summary>
        internal static string StopInProgress {
            get {
                return ResourceManager.GetString("StopInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminer.
        /// </summary>
        internal static string TerminateLabel {
            get {
                return ResourceManager.GetString("TerminateLabel", resourceCulture);
            }
        }
    }
}
