//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.3607
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace MIProgram.DataAccess {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("metalimpact")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class metalimpact : global::System.Data.DataSet {
        
        private mi_reviewsDataTable tablemi_reviews;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public metalimpact() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected metalimpact(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["mi_reviews"] != null)) {
                    base.Tables.Add(new mi_reviewsDataTable(ds.Tables["mi_reviews"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public mi_reviewsDataTable mi_reviews {
            get {
                return this.tablemi_reviews;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            metalimpact cln = ((metalimpact)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["mi_reviews"] != null)) {
                    base.Tables.Add(new mi_reviewsDataTable(ds.Tables["mi_reviews"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablemi_reviews = ((mi_reviewsDataTable)(base.Tables["mi_reviews"]));
            if ((initTable == true)) {
                if ((this.tablemi_reviews != null)) {
                    this.tablemi_reviews.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "metalimpact";
            this.Prefix = "";
            this.Locale = new global::System.Globalization.CultureInfo("en-US");
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablemi_reviews = new mi_reviewsDataTable();
            base.Tables.Add(this.tablemi_reviews);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializemi_reviews() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            metalimpact ds = new metalimpact();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void mi_reviewsRowChangeEventHandler(object sender, mi_reviewsRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class mi_reviewsDataTable : global::System.Data.TypedTableBase<mi_reviewsRow> {
            
            private global::System.Data.DataColumn columnpn_id;
            
            private global::System.Data.DataColumn columnpn_date;
            
            private global::System.Data.DataColumn columnpn_title;
            
            private global::System.Data.DataColumn columnpn_text;
            
            private global::System.Data.DataColumn columnpn_reviewer;
            
            private global::System.Data.DataColumn columnpn_email;
            
            private global::System.Data.DataColumn columnpn_score;
            
            private global::System.Data.DataColumn columnpn_cover;
            
            private global::System.Data.DataColumn columnpn_url;
            
            private global::System.Data.DataColumn columnpn_url_title;
            
            private global::System.Data.DataColumn columnpn_hits;
            
            private global::System.Data.DataColumn columnpn_language;
            
            private global::System.Data.DataColumn columnpn_upc;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public mi_reviewsDataTable() {
                this.TableName = "mi_reviews";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal mi_reviewsDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected mi_reviewsDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_idColumn {
                get {
                    return this.columnpn_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_dateColumn {
                get {
                    return this.columnpn_date;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_titleColumn {
                get {
                    return this.columnpn_title;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_textColumn {
                get {
                    return this.columnpn_text;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_reviewerColumn {
                get {
                    return this.columnpn_reviewer;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_emailColumn {
                get {
                    return this.columnpn_email;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_scoreColumn {
                get {
                    return this.columnpn_score;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_coverColumn {
                get {
                    return this.columnpn_cover;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_urlColumn {
                get {
                    return this.columnpn_url;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_url_titleColumn {
                get {
                    return this.columnpn_url_title;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_hitsColumn {
                get {
                    return this.columnpn_hits;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_languageColumn {
                get {
                    return this.columnpn_language;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn pn_upcColumn {
                get {
                    return this.columnpn_upc;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public mi_reviewsRow this[int index] {
                get {
                    return ((mi_reviewsRow)(this.Rows[index]));
                }
            }
            
            public event mi_reviewsRowChangeEventHandler mi_reviewsRowChanging;
            
            public event mi_reviewsRowChangeEventHandler mi_reviewsRowChanged;
            
            public event mi_reviewsRowChangeEventHandler mi_reviewsRowDeleting;
            
            public event mi_reviewsRowChangeEventHandler mi_reviewsRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Addmi_reviewsRow(mi_reviewsRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public mi_reviewsRow Addmi_reviewsRow(string pn_id, string pn_date, string pn_title, string pn_text, string pn_reviewer, string pn_email, string pn_score, string pn_cover, string pn_url, string pn_url_title, string pn_hits, string pn_language, string pn_upc) {
                mi_reviewsRow rowmi_reviewsRow = ((mi_reviewsRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        pn_id,
                        pn_date,
                        pn_title,
                        pn_text,
                        pn_reviewer,
                        pn_email,
                        pn_score,
                        pn_cover,
                        pn_url,
                        pn_url_title,
                        pn_hits,
                        pn_language,
                        pn_upc};
                rowmi_reviewsRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowmi_reviewsRow);
                return rowmi_reviewsRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                mi_reviewsDataTable cln = ((mi_reviewsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new mi_reviewsDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnpn_id = base.Columns["pn_id"];
                this.columnpn_date = base.Columns["pn_date"];
                this.columnpn_title = base.Columns["pn_title"];
                this.columnpn_text = base.Columns["pn_text"];
                this.columnpn_reviewer = base.Columns["pn_reviewer"];
                this.columnpn_email = base.Columns["pn_email"];
                this.columnpn_score = base.Columns["pn_score"];
                this.columnpn_cover = base.Columns["pn_cover"];
                this.columnpn_url = base.Columns["pn_url"];
                this.columnpn_url_title = base.Columns["pn_url_title"];
                this.columnpn_hits = base.Columns["pn_hits"];
                this.columnpn_language = base.Columns["pn_language"];
                this.columnpn_upc = base.Columns["pn_upc"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnpn_id = new global::System.Data.DataColumn("pn_id", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_id);
                this.columnpn_date = new global::System.Data.DataColumn("pn_date", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_date);
                this.columnpn_title = new global::System.Data.DataColumn("pn_title", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_title);
                this.columnpn_text = new global::System.Data.DataColumn("pn_text", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_text);
                this.columnpn_reviewer = new global::System.Data.DataColumn("pn_reviewer", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_reviewer);
                this.columnpn_email = new global::System.Data.DataColumn("pn_email", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_email);
                this.columnpn_score = new global::System.Data.DataColumn("pn_score", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_score);
                this.columnpn_cover = new global::System.Data.DataColumn("pn_cover", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_cover);
                this.columnpn_url = new global::System.Data.DataColumn("pn_url", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_url);
                this.columnpn_url_title = new global::System.Data.DataColumn("pn_url_title", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_url_title);
                this.columnpn_hits = new global::System.Data.DataColumn("pn_hits", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_hits);
                this.columnpn_language = new global::System.Data.DataColumn("pn_language", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_language);
                this.columnpn_upc = new global::System.Data.DataColumn("pn_upc", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnpn_upc);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public mi_reviewsRow Newmi_reviewsRow() {
                return ((mi_reviewsRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new mi_reviewsRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(mi_reviewsRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.mi_reviewsRowChanged != null)) {
                    this.mi_reviewsRowChanged(this, new mi_reviewsRowChangeEvent(((mi_reviewsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.mi_reviewsRowChanging != null)) {
                    this.mi_reviewsRowChanging(this, new mi_reviewsRowChangeEvent(((mi_reviewsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.mi_reviewsRowDeleted != null)) {
                    this.mi_reviewsRowDeleted(this, new mi_reviewsRowChangeEvent(((mi_reviewsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.mi_reviewsRowDeleting != null)) {
                    this.mi_reviewsRowDeleting(this, new mi_reviewsRowChangeEvent(((mi_reviewsRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Removemi_reviewsRow(mi_reviewsRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                metalimpact ds = new metalimpact();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "mi_reviewsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class mi_reviewsRow : global::System.Data.DataRow {
            
            private mi_reviewsDataTable tablemi_reviews;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal mi_reviewsRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablemi_reviews = ((mi_reviewsDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_id {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_id\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_date {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_dateColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_date\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_dateColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_title {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_titleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_title\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_titleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_text {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_textColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_text\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_textColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_reviewer {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_reviewerColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_reviewer\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_reviewerColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_email {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_emailColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_email\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_emailColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_score {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_scoreColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_score\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_scoreColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_cover {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_coverColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_cover\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_coverColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_url {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_urlColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_url\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_urlColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_url_title {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_url_titleColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_url_title\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_url_titleColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_hits {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_hitsColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_hits\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_hitsColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_language {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_languageColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_language\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_languageColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string pn_upc {
                get {
                    try {
                        return ((string)(this[this.tablemi_reviews.pn_upcColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("La valeur pour la colonne \'pn_upc\' dans la table \'mi_reviews\' est DBNull.", e);
                    }
                }
                set {
                    this[this.tablemi_reviews.pn_upcColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_idNull() {
                return this.IsNull(this.tablemi_reviews.pn_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_idNull() {
                this[this.tablemi_reviews.pn_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_dateNull() {
                return this.IsNull(this.tablemi_reviews.pn_dateColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_dateNull() {
                this[this.tablemi_reviews.pn_dateColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_titleNull() {
                return this.IsNull(this.tablemi_reviews.pn_titleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_titleNull() {
                this[this.tablemi_reviews.pn_titleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_textNull() {
                return this.IsNull(this.tablemi_reviews.pn_textColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_textNull() {
                this[this.tablemi_reviews.pn_textColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_reviewerNull() {
                return this.IsNull(this.tablemi_reviews.pn_reviewerColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_reviewerNull() {
                this[this.tablemi_reviews.pn_reviewerColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_emailNull() {
                return this.IsNull(this.tablemi_reviews.pn_emailColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_emailNull() {
                this[this.tablemi_reviews.pn_emailColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_scoreNull() {
                return this.IsNull(this.tablemi_reviews.pn_scoreColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_scoreNull() {
                this[this.tablemi_reviews.pn_scoreColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_coverNull() {
                return this.IsNull(this.tablemi_reviews.pn_coverColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_coverNull() {
                this[this.tablemi_reviews.pn_coverColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_urlNull() {
                return this.IsNull(this.tablemi_reviews.pn_urlColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_urlNull() {
                this[this.tablemi_reviews.pn_urlColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_url_titleNull() {
                return this.IsNull(this.tablemi_reviews.pn_url_titleColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_url_titleNull() {
                this[this.tablemi_reviews.pn_url_titleColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_hitsNull() {
                return this.IsNull(this.tablemi_reviews.pn_hitsColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_hitsNull() {
                this[this.tablemi_reviews.pn_hitsColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_languageNull() {
                return this.IsNull(this.tablemi_reviews.pn_languageColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_languageNull() {
                this[this.tablemi_reviews.pn_languageColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ispn_upcNull() {
                return this.IsNull(this.tablemi_reviews.pn_upcColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setpn_upcNull() {
                this[this.tablemi_reviews.pn_upcColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class mi_reviewsRowChangeEvent : global::System.EventArgs {
            
            private mi_reviewsRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public mi_reviewsRowChangeEvent(mi_reviewsRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public mi_reviewsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591